# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_eq.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_new_eq(object):
    def setupUi(self, new_eq):
        new_eq.setObjectName("new_eq")
        new_eq.resize(368, 175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(new_eq.sizePolicy().hasHeightForWidth())
        new_eq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Latin Modern Roman")
        font.setPointSize(16)
        new_eq.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_eq)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(new_eq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(new_eq)
        font = QtGui.QFont()
        font.setItalic(True)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(50, 70))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lxnum = QtWidgets.QLineEdit(self.widget_2)
        self.lxnum.setFrame(True)
        self.lxnum.setAlignment(QtCore.Qt.AlignCenter)
        self.lxnum.setObjectName("lxnum")
        self.verticalLayout_2.addWidget(self.lxnum)
        self.lxline = QtWidgets.QFrame(self.widget_2)
        self.lxline.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lxline.setFrameShape(QtWidgets.QFrame.HLine)
        self.lxline.setObjectName("lxline")
        self.verticalLayout_2.addWidget(self.lxline)
        self.lxdenom = QtWidgets.QLineEdit(self.widget_2)
        self.lxdenom.setAlignment(QtCore.Qt.AlignCenter)
        self.lxdenom.setObjectName("lxdenom")
        self.verticalLayout_2.addWidget(self.lxdenom)
        self.horizontalLayout.addWidget(self.widget_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMaximumSize(QtCore.QSize(50, 70))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lnum = QtWidgets.QLineEdit(self.widget_3)
        self.lnum.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lnum.setAlignment(QtCore.Qt.AlignCenter)
        self.lnum.setObjectName("lnum")
        self.verticalLayout_3.addWidget(self.lnum)
        self.lline = QtWidgets.QFrame(self.widget_3)
        self.lline.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lline.setFrameShape(QtWidgets.QFrame.HLine)
        self.lline.setObjectName("lline")
        self.verticalLayout_3.addWidget(self.lline)
        self.ldenom = QtWidgets.QLineEdit(self.widget_3)
        self.ldenom.setAlignment(QtCore.Qt.AlignCenter)
        self.ldenom.setObjectName("ldenom")
        self.verticalLayout_3.addWidget(self.ldenom)
        self.horizontalLayout.addWidget(self.widget_3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setMaximumSize(QtCore.QSize(50, 70))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rxnum = QtWidgets.QLineEdit(self.widget_4)
        self.rxnum.setAlignment(QtCore.Qt.AlignCenter)
        self.rxnum.setObjectName("rxnum")
        self.verticalLayout_4.addWidget(self.rxnum)
        self.rxline = QtWidgets.QFrame(self.widget_4)
        self.rxline.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rxline.setFrameShape(QtWidgets.QFrame.HLine)
        self.rxline.setObjectName("rxline")
        self.verticalLayout_4.addWidget(self.rxline)
        self.rxdenom = QtWidgets.QLineEdit(self.widget_4)
        self.rxdenom.setAlignment(QtCore.Qt.AlignCenter)
        self.rxdenom.setObjectName("rxdenom")
        self.verticalLayout_4.addWidget(self.rxdenom)
        self.horizontalLayout.addWidget(self.widget_4)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setMaximumSize(QtCore.QSize(50, 70))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rnum = QtWidgets.QLineEdit(self.widget_5)
        self.rnum.setAlignment(QtCore.Qt.AlignCenter)
        self.rnum.setObjectName("rnum")
        self.verticalLayout_5.addWidget(self.rnum)
        self.rline = QtWidgets.QFrame(self.widget_5)
        self.rline.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rline.setFrameShape(QtWidgets.QFrame.HLine)
        self.rline.setObjectName("rline")
        self.verticalLayout_5.addWidget(self.rline)
        self.rdenom = QtWidgets.QLineEdit(self.widget_5)
        self.rdenom.setAlignment(QtCore.Qt.AlignCenter)
        self.rdenom.setObjectName("rdenom")
        self.verticalLayout_5.addWidget(self.rdenom)
        self.horizontalLayout.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(new_eq)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(new_eq)
        self.buttonBox.accepted.connect(new_eq.accept)
        self.buttonBox.rejected.connect(new_eq.reject)
        QtCore.QMetaObject.connectSlotsByName(new_eq)

    def retranslateUi(self, new_eq):
        _translate = QtCore.QCoreApplication.translate
        new_eq.setWindowTitle(_translate("new_eq", "Dialog"))
        self.label.setText(_translate("new_eq", "Nouvelle équation :"))
        self.label_3.setText(_translate("new_eq", "x +"))
        self.label_2.setText(_translate("new_eq", " = "))
        self.label_4.setText(_translate("new_eq", "x +"))

from . import resources_rc
